[package]
name = "ensure_cfg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "5"
toml = "0.7"
thiserror = "1"
dunce = "1"